name: XPWars
version: ${project.version}
description: '${BUILD_NUMBER}' # do not touch please, this is to make update checker working for snapshots
main: nfn11.xpwars.XPWars
api-version: 1.13
depend:
- BedWars
softdepend:
- PlaceholderAPI
load: POSTWORLD
author: notfoundname11, ConnorLinfoot (ActionBarAPI), ScreamingSandals (SimpleInventories)
