name: XPWars
version: ${project.version}
main: nfn11.xpwars.XPWars
api-version: 1.13
depend:
- BedWars
softdepend:
- PlaceholderAPI
load: POSTWORLD
author: notfoundname11, ConnorLinfoot (ActionBarAPI), ScreamingSandals (SimpleInventories)
