name: Builds
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - run: mvn -B package --file pom.xml
    - run: 'mv target/XPWars-1.3-null.jar target/XPWars-1.3-GITHUB-${{ github.run_number }}.jar'
    - uses: actions/upload-artifact@v2.0.1
      with:
        name: "XPWars-1.3-GITHUB-${{ github.run_number }}"
        path: "target/XPWars-1.3-GITHUB-${{ github.run_number }}.jar"
