# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Java 8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Unshallow
      run: git fetch --unshallow --quiet
    - name: Maven build
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: "ScreamingBedwarsAddon"
        path: "/target/ScreamingBedwarsAddon.jar"
