# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Snapshots for testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - run: mvn -B package --file pom.xml
    - uses: einaregilsson/build-number@v1
      with:
        token: ${{secrets.github_token}}
    - uses: actions/upload-artifact@v2
      with:
        name: "XPWars-build $BUILD_NUMBER"
        path: "./target/XPWars-*.jar"
